### ISSUE TITLE
Tradable balance check is not working

### ISSUE THREAD

**Issue by kinbitz** [PyWaves/BlackBot#35]
The tradable balance check is not working properly as the bot still tries to place orders even when there is not enough balance.

**Comment by kinbitz** [comment]
Probably this like should be changed to if order_type == "buy" and balance_price > tranche_size
https://github.com/PyWaves/BlackBot/blob/83838873d169563fd5f4ba06cbf1cf8000eb43a4/BlackBot.py#L45

**Comment by jansenmarc** [comment]
Ok, that's indeed the most recent version.

Did you try the following formula:

10(8 + priceAssetDecimals - amountAssetDecimals)

**Comment by kinbitz** [comment]
I tried with tranche_size * price / 10 ** 6 and it works for checking the buying balance. For checking the  selling balance it is enough the  balance_amount >= tranche_size works, because there is no need to multiply by the price.

**Comment by kinbitz** [comment]
After testing I concluded this check needs to be separately done within the if statement of the buy and sell side, otherwise still the bot tries to place an order without enough balance.

**Comment by jansenmarc** [comment]
Great, but does the above formula work for you?

**Comment by kinbitz** [comment]
Still sometimes it doesn't work for checking the selling side balance and I am not able to find the reason. I tried different things, but nothing worked. For checking the buying side balance it never fails.

**Comment by kinbitz** [comment]
Could the reason be that the matcher takes some time before updating the tradable balance? Do we have a way to stop the script until we get confirmation from the matcher?

**Comment by jansenmarc** [comment]
I doubt that this is the point. Tradable balance is the balance on the account.

**Comment by kinbitz** [comment]
I logged tradable balance after each step and it was diminishing after every sell order posted to the matcher.

**Comment by jansenmarc** [comment]
That's not a blackbot problem.

**Comment by kinbitz** [comment]
Now after extensive testing I found that I need to use tranche_size*(price/10**(4 + PAIR.asset2.decimals - PAIR.asset1.decimals) for this check to work.
