### ISSUE TITLE
NOT Compromised

### ISSUE THREAD

**Issue by Germinsky** [PyWaves/BlackBot#4]
This account is hacking wallets 3PA7s6dBUicge7uVwe6uLePvSj9sc8NMynR

**Comment by trgpwild** [comment]
What do you mean? The problem is with the code or this is a denouncement?

**Comment by Germinsky** [comment]
I am trying to figure that out, I have been using this script for 3 days with no issues and today my waves account was drained of all valuable assets. Fresh install on linux setup.

**Comment by trgpwild** [comment]
Hmm... I was thinking on create an account just to test this script. Now I see this is really the better choice.

**Comment by Germinsky** [comment]
the code is solid, my bad!

**Comment by ttt982** [comment]
status = order['status']
TypeError: string indices must be integers

problem??
