### ISSUE TITLE
started getting a error

### ISSUE THREAD

**Issue by kinbitz** [PyWaves/BlackBot#8]
Since few days I am getting an error as follows:

Traceback (most recent call last):
  File "BlackBot.py", line 126, in <module>
    BLACKBOT.deleteOrderHistory(PAIR)
  File "/usr/local/lib/python2.7/dist-packages/pywaves/address.py", line 888, in deleteOrderHistory
    pywaves.wrapper('/matcher/orderbook/%s/%s/delete' % ('WAVES' if assetPair.asset1.assetId == '' else assetPair.asset1.assetId, 'WAVES' if assetPair.asset2.assetId == '' else assetPair.asset2.assetId), data, host=pywaves.MATCHER)
  File "/usr/local/lib/python2.7/dist-packages/pywaves/__init__.py", line 130, in wrapper
    req = requests.post('%s%s' % (host, api), data=postData, headers={'content-type': 'application/json'}).json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by sabotagebeats** [comment]
I'm getting the same error.

**Comment by sabotagebeats** [comment]
https://github.com/PyWaves/PyWaves/issues/51

**Comment by sabotagebeats** [comment]
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by PyWaves** [comment]
Are you sure you are using the latest version of pywaves?

**Comment by kinbitz** [comment]
Yes, I am using version 0.8.18.

**Comment by PyWaves** [comment]
Please send some example code that shows the problem.

**Comment by kinbitz** [comment]
I think this is related to issue #12 . I am using the WAVES to USD trading pair

**Comment by PyWaves** [comment]
If so, it should be fixed by now...

kinbitz <notifications@github.com> schrieb am Do., 30. Aug. 2018, 15:42:

**Comment by kinbitz** [comment]
I could check it only now and it works fine. Thank you.
